### ISSUE TITLE
Add unicode emoji mappings

### ISSUE THREAD

**Issue by PVince81** [fcitx/fcitx-table-other#4]
Many emojis are available as unicode characters.

The idea is to use a mapping like this one: http://www.emoji-cheat-sheet.com/

For example `:tiger:` maps to :tiger: (unicode `🐯`)

**Comment by tombh** [comment]
We kind of have this already, with the CTRL+ALT+SHIFT+U of unicode support. I can type "tears of joy" for example and get 😂 But I agree that the more concise `:joy:` shortcodes are much better.

**Comment by wengxt** [comment]
Personally, I prefer using quickphrase (https://fcitx-im.org/wiki/QuickPhrase) over a separate table in fcitx-table. There's a existing onee in main repo though it's not based on unicode (https://github.com/fcitx/fcitx/blob/master/src/module/quickphrase/quickphrase.d/emoji.mb). 

As for emoji-cheat-sheet.com, I didn't see a clear license that we can directly reuse their work. Someone already brought up the issue here: https://github.com/arvida/emoji-cheat-sheet.com/issues/352

So probably we need to sort out these ourselves. Any help is appreciated.

**Comment by Arthur2e5** [comment]
There is a npm library called emoji at https://github.com/node-modules/emoji (MIT), and apparently its data comes from https://github.com/iamcal/php-emoji/blob/master/table.htm.

See also https://github.com/mroth/emoji-data-js/tree/master/vendor/emoji-data.

(Some 2-year-old data… hmm
